spring:
  datasource:
    username: root
    password: yxx
    url: jdbc:mysql://localhost:3306/competitive?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false

      web-stat-filter:
        enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
shiro:
  loginUrl: /login.html
  sessionManager:
  # disable URL session rewriting
    sessionIdUrlRewritingEnabled: false
logging:
  level:
    com:
      competitive:
        dao=debug: